name: my-static-site
region: nyc
static_sites:
  - name: frontend
    github:
      repo: laliagaTimex/AI_Test
      branch: main
      deploy_on_push: true
    source_dir: /
    index_document: index.html
    catchall_document: index.html